name: sanitizer

on:
  push:
    branches: [master, dev0.3.0]
  pull_request:
    branches: [master, dev0.3.0]

defaults:
  run:
    shell: bash

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Sanitizer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Dfintamath_build_tests=ON -Dfintamath_enable_sanitizers=ON
        env:
          CC: gcc
          CXX: g++

      - name: Build
        working-directory: ${{github.workspace}}
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C${{env.BUILD_TYPE}}
